/**
 * ToDoBackend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ToDoItemResponse } from './toDoItemResponse';

export interface GroupResponse { 
    name?: string;
    color?: string;
    isDefault?: boolean;
    toDoItems?: Array<ToDoItemResponse>;
    uid?: string;
    createdAt?: Date;
    createdBy?: string;
    modifiedAt?: Date;
    modifiedBy?: string;
}