# custom-nginx-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: ynozar/todo-api:latest  # Replace with your image
        env:
          - name: DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_PROD_CONNECTION
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  type: LoadBalancer  # Use LoadBalancer for external access
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: todo-backend
