# Dockerfile

# Stage 1: Build Angular application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./

COPY . .
RUN npm install
RUN npm install -g @angular/cli
RUN npm run build --prod

# Stage 2: Serve Angular application using nginx
FROM nginx:alpine
COPY --from=builder /app/dist/ToDo /usr/share/nginx/html
#Copy default nginx configuration
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
