name: Deploy to GCP

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
        default: 'latest'
      action:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit Short Hash'
        required: true
        default: 'latest'
      action:
        type: choice
        description: 'Choose the action to perform'
        required: true
        default: 'plan'
        options:
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        #with:
        #  ref: ${{ github.event.inputs.commit_hash || 'main' }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Terraform version
        run: terraform version

      - name: Initialize Terraform
        run: |
          cd Terraform # Change to your Terraform directory
          terraform init

      - name: Terraform Run
        run: |
          cd Terraform # Change to your Terraform directory
          echo "Commit Hash: ${{ inputs.commit_hash }}"
          action=${{ inputs.action }}
          if [[ "$action" == "apply" ]]; then
            terraform apply -auto-approve
          else
            terraform plan
          fi

        env:
          TF_VAR_COMMIT_HASH: ${{ inputs.commit_hash }}
          TF_VAR_DB_PROD_CONNECTION: ${{ secrets.DB_PROD_CONNECTION }}
          TF_VAR_RSA_PRIVATE: ${{ secrets.RSA_PRIVATE }}
          TF_VAR_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
