name: Build and Deploy

on:
  workflow_dispatch:
permissions:
  packages: write
  id-token: write
  attestations: write
jobs:
  build-and-publish:
    uses: .github/workflows/dockerhub-publish.yml

  get-sha:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.get_sha.outputs.sha_short }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  deploy:
    needs: get-sha
    uses: ./.github/workflows/deploy-to-gcp.yml
    with:
      commit_hash: ${{ needs.get-sha.outputs.sha_short }}
      action: 'apply'
