name: Publish and Deploy

on: 
  workflow_dispatch:
jobs:
  publish_to_dockerhub:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.get_sha.outputs.sha_short }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push UI Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./UI
          file: ./UI/Dockerfile.prod
          push: true
          tags: ynozar/todo-ui:${{ steps.get_sha.outputs.sha_short }}, ynozar/todo-ui:latest

      - name: Build and push Backend Docker image
        id: push-2
        uses: docker/build-push-action@v5
        with:
          context: ./ToDoBackend/ToDoBackend
          file: ./ToDoBackend/ToDoBackend/Dockerfile
          push: true
          tags: ynozar/todo-api:${{ steps.get_sha.outputs.sha_short }}, ynozar/todo-api:latest
  push_to_azure:
    needs: publish_to_dockerhub
    name: deploy to azure
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ needs.publish_to_dockerhub.outputs.commit-sha }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Build and deploy UI Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: ui
          resourceGroup: todo-app
          imageToDeploy: ynozar/todo-ui:$COMMIT_SHA

      - name: Build and deploy Backend Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: backend
          resourceGroup: todo-app
          imageToDeploy: ynozar/todo-backend:$COMMIT_SHA
